---
- name: install satyr packages
  package: name={{ item }} state=latest
  become: true
  loop: "{{ satyr_packages }}"

- name: install libreport packages
  package: name={{ item }} state=latest
  become: true
  loop: "{{ libreport_packages }}"

- name: install abrt packages
  package: name={{ item }} state=latest
  become: true
  loop: "{{ abrt_packages }}"

- name: start abrtd service
  become: true
  service:
    name: abrtd
    state: started
    enabled: yes

- name: start abrt-ccpp service
  become: true
  service:
    name: abrt-ccpp
    state: started
    enabled: yes

- name: start abrt-oops service
  become: true
  service:
    name: abrt-oops
    state: started
    enabled: yes

- name: start abrt-vmcore service
  become: true
  service:
    name: abrt-vmcore
    state: started
    enabled: yes

- name: configure FAF url
  become: true
  lineinfile:
    path: /etc/libreport/plugins/ureport.conf
    regexp: '^URL ='
    insertafter: '^# URL ='
    line: 'URL = {{ faf_url }}'
